import type { Debt } from "./constants";
import { uid } from "./format";

export function buildDemoDebts(): Debt[] {
  return [
    {
      id: uid(),
      name: "Cartão exemplo",
      type: "cartao",
      balance: 4500,
      rate: 0,
      penaltyRate: 14,
      graceDaysLeft: 0,
      dueDate: "",
      discountPct: 0,
      minPayment: 675,
      note: "Exemplo — apague quando quiser.",
      paid: 0,
      done: false,
    },
    {
      id: uid(),
      name: "Cheque especial exemplo",
      type: "cheque_especial",
      balance: 2000,
      rate: 8,
      penaltyRate: 8,
      graceDaysLeft: 0,
      dueDate: "",
      discountPct: 0,
      minPayment: 2000,
      note: "Exemplo — taxa alta, prioridade máxima.",
      paid: 0,
      done: false,
    },
    {
      id: uid(),
      name: "Empréstimo exemplo A",
      type: "emprestimo",
      balance: 8000,
      rate: 5.5,
      penaltyRate: 5.5,
      graceDaysLeft: 0,
      dueDate: "",
      discountPct: 20,
      minPayment: 800,
      note: "Exemplo — banco ofereceu desconto de 20%.",
      paid: 0,
      done: false,
    },
    {
      id: uid(),
      name: "Empréstimo exemplo B",
      type: "emprestimo",
      balance: 3000,
      rate: 4.5,
      penaltyRate: 4.5,
      graceDaysLeft: 0,
      dueDate: "",
      discountPct: 0,
      minPayment: 500,
      note: "Exemplo — dívida média.",
      paid: 0,
      done: false,
    },
    {
      id: uid(),
      name: "Financiamento exemplo",
      type: "financiamento",
      balance: 45000,
      rate: 1.2,
      penaltyRate: 1.2,
      graceDaysLeft: 0,
      dueDate: "",
      discountPct: 0,
      minPayment: 750,
      note: "Exemplo — taxa baixa, longo prazo.",
      paid: 0,
      done: false,
    },
  ];
}
